version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-cache-{{ .Branch }}
            - yarn-cache-master
      - run:
          name: install dependencies
          command: ./bin/run.sh install
      - save_cache:
          key: yarn-cache-{{ .Branch }}-{{ .BuildNum }}	
          paths:
            - /home/circleci/.cache/yarn/v1
      - run:
          name: tests
          command: ./bin/run.sh test
      - run:
          name: upload coverage
          command: yarn coverage
